#!/usr/bin/env bash
#This Bash script displayshe content of the current directory in list format where only the part of the name after the first dash is displayed
for ((i = 0 ; i < 1 ; i++));
do
echo ""
done 
